CREATE TABLE IF NOT EXISTS teste (
 ID SERIAL PRIMARY KEY,
	nome VARCHAR(50) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP 
);

DROP TABLE IF EXISTS teste;

CREATE TABLE IF NOT EXISTS teste (
cpf VARCHAR(11) NOT NULL,
	nome VARCHAR(50) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	PRIMARY KEY (cpf)
);

INSERT INTO teste(cpf,nome,created_at)
VALUES ('22233300016', 'Jose Colmeia', '2020-06-08 12:00:00');

UPDATE teste SET nome = 'Pedro Alvares' WHERE cpf = '22233300016';

SELECT * FROM teste;
